# Generated by Django 5.2.7 on 2025-10-24 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_tournament_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='prize_pool',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='status',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='total_teams',
        ),
        migrations.AddField(
            model_name='tournament',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
