# Generated by Django 5.2.7 on 2025-10-24 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_remove_tournament_prize_pool_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
