# Generated by Django 5.2.7 on 2025-10-24 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0006_tournament_prize_pool_alter_tournament_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='total_teams',
            field=models.PositiveIntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='prize_pool',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
