# Generated by Django 5.2.7 on 2025-10-24 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0008_alter_team_created_by_alter_team_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='total_teams',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
