# Generated by Django 5.2.7 on 2025-10-22 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=200)),
                ('price', models.PositiveIntegerField()),
                ('rating', models.CharField(max_length=5)),
                ('location', models.CharField(max_length=200)),
                ('sport', models.CharField(choices=[('badminton', 'Badminton'), ('basketball', 'Basketball'), ('billiard', 'Billiard'), ('e-sport', 'E-Sport'), ('futsal', 'Futsal'), ('golf', 'Golf'), ('mini soccer', 'Mini Soccer'), ('padel', 'Padel'), ('pickleball', 'Pickleball'), ('sepak bola', 'Sepak Bola'), ('squash', 'Squash'), ('tenis meja', 'Tenis Meja'), ('tennis', 'Tennis')], max_length=20)),
                ('facilities', models.JSONField(default=list)),
                ('url', models.CharField(max_length=200)),
            ],
        ),
    ]
