# Generated by Django 5.2.7 on 2025-10-23 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='blog',
            name='summary',
            field=models.TextField(default='Ringkasan Sementara', max_length=300),
            preserve_default=False,
        ),
    ]
