# Generated by Django 5.2.7 on 2025-10-23 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blog_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
