# Generated by Django 5.2.8 on 2025-12-21 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_blog_updated_at_blog_blog_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(blank=True, choices=[('padel', 'Padel'), ('basket', 'Basket'), ('futsal', 'Futsal'), ('badminton', 'Badminton'), ('Health & Fitness', 'Health & Fitness')], max_length=100, null=True),
        ),
    ]
