# Generated by Django 5.2.8 on 2025-12-21 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('padel', 'Padel'), ('basket', 'Basket'), ('futsal', 'Futsal'), ('badminton', 'Badminton'), ('Health & Fitness', 'Health & Fitness')], default='padel', max_length=50),
        ),
    ]
